__author__ = "Nico Schlömer"
__email__ = "nico.schloemer@gmail.com"
__copyright__ = f"Copyright (c) 2017-2020, {__author__} <{__email__}>"
__license__ = "License :: OSI Approved :: MIT License"
__version__ = "0.3.5"
__status__ = "Development Status :: 5 - Production/Stable"
